### ISSUE TITLE
Add a !help command

### ISSUE THREAD

**Issue by pixeldesu** [pixeldesu/himeka#3]
Users need to know what `message`-type commands a bot supports, of course!

**To Do:**
- Add a static `description` field to commands (and re-add it to existing commands)
- Refactor the `CommandManager` so it doesn't create handlers on initialization, we only need the map of commands, especially the `message` ones
- Find a way to cleanly pass an instance of `CommandManager` to a command (propose and discuss any ideas for this!)
- Instead of flooding the server with help command output, send a direct message to the user who requested help.

**Comment by raccube** [comment]
Should close this issue as it's been fixed in #5

**Comment by raccube** [comment]
My fault for not adding a "Fixes ..." clause in the description
